### ISSUE TITLE
running the docker and trying to create a columnstore table gives following error

### ISSUE THREAD

**Issue by megabites2013** [mariadb-corporation/mariadb-columnstore-docker#20]
running the docker and trying to create a columnstore table gives following error:

**SQL Error [1815] [HY000]: (conn=315) Internal error: Cannot execute the statement. DBRM is read only!**

while week ago it is working without issue, what has been changed?

**Comment by flopana** [comment]
Can confirm I have the same problem with the new version

**Comment by DNL-paris** [comment]
Hello,

We were having the same issue and we solved it by configuring our **docker-compose.yml** file like this : 
```
services:
    db:
        image: 'mariadb/columnstore'
        hostname: db_cs
        shm_size: 512m
        environment:
            - CLUSTER=false
            - PM1=db_cs
```
You need to set up those environment values to make it work, specially PM1 part.

Hope this will be helpful,
